use serde::{Deserialize, Serialize};
use std::{collections::HashMap, error::Error, hash::Hash};

// declarations
// ======================

enum Instruction {
    MV = 0,
    LB = 1,
    LI = 2,
    SB = 3,

    ADD = 10,
    ADDI = 11,
    SUB = 12,
    AND = 13,
    ANDI = 14,
    OR = 15,
    ORI = 16,
    XOR = 17,
    XORI = 18,
    NOT = 19,

    CMP = 32,
    BE = 33,
    BNE = 34,
    BGE = 35,
    BLT = 36,

    NOP = 62,
    HLT = 63,
}

enum Register {
    R0 = 8,
    R1 = 9,
    R2 = 10,
    R3 = 11,
    R4 = 12,
    R5 = 13,
    R6 = 14,
    R7 = 15,
}

impl Register {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "r0" => Some(Register::R0),
            "r1" => Some(Register::R1),
            "r2" => Some(Register::R2),
            "r3" => Some(Register::R3),
            "r4" => Some(Register::R4),
            "r5" => Some(Register::R5),
            "r6" => Some(Register::R6),
            "r7" => Some(Register::R7),
            _ => None,
        }
    }
}

// ======================

/// Token
/// must implement Clone and Token trait
/// Token trait is used to convert a token to a tree node
pub trait Token: Clone {
    fn to_tree_node(&self) -> ParsingTreeNode;
}

pub struct ParsingTreeNode {
    pub symbol_type: String,
    pub data: String,
    pub children: Vec<ParsingTreeNode>,
}

impl ParsingTreeNode {
    pub fn build(symbol_type: String, data: String, children: Vec<ParsingTreeNode>) -> Self {
        ParsingTreeNode {
            symbol_type,
            data,
            children,
        }
    }
}

/// NodePair
/// a pair of a node and a state.
/// (TreeNode, state)
pub struct NodePair(ParsingTreeNode, usize);
impl NodePair {
    pub fn new(node: ParsingTreeNode, state: usize) -> Self {
        NodePair(node, state)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReduceDerivation {
    pub left: String,
    pub right: Vec<String>,
}

impl PartialEq for ReduceDerivation {
    fn eq(&self, other: &Self) -> bool {
        self.left == other.left && self.right == other.right
    }
}

impl Eq for ReduceDerivation {}

impl Hash for ReduceDerivation {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.left.hash(state);
        self.right.hash(state);
    }
}

impl ReduceDerivation {
    pub fn build(left: String, right: Vec<String>) -> Self {
        ReduceDerivation { left, right }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Action {
    Shift(usize),
    Reduce(ReduceDerivation),
    Accept,
    Error,
}

#[derive(Serialize, Deserialize)]
pub struct State {
    pub actions: HashMap<String, Action>,
}

impl State {
    pub fn new() -> Self {
        State {
            actions: HashMap::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Default)]
pub struct ActionTable {
    pub states: Vec<State>,
}

impl ActionTable {
    pub fn get_action(&self, state: usize, symbol: &str) -> Option<&Action> {
        self.states[state].actions.get(symbol)
    }
}

#[derive(Default)]
pub struct RParser {
    action_table: ActionTable,
    handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>>,
    // variables
    // ======================
    pub gen_code: Vec<u8>,
    // ======================
}

impl RParser {
    pub const END_SYMBOL: &'static str = "__$__";
    pub const EPSILON_SYMBOL: &'static str = "__EPSILON__";
    pub const DUMMY_START_SYMBOL: &'static str = "__DUMMY_START__";

    pub fn new() -> Self {
        // action table generated by rparser
        // ======================
        let action_table: ActionTable =  serde_json::from_str(r#"{"states":[{"actions":{"add":{"Shift":2},"li":{"Shift":59},"addi":{"Shift":14},"or":{"Shift":36},"S":{"Shift":65},"program":{"Shift":64},"nop":{"Shift":40},"xori":{"Shift":55},"instructions":{"Shift":63},"mv":{"Shift":6},"not":{"Shift":45},"__$__":"Accept","cmp":{"Shift":47},"lb":{"Shift":10},"instruction":{"Shift":1},"sb":{"Shift":22},"andi":{"Shift":26},"hlt":{"Shift":30},"and":{"Shift":41},"xor":{"Shift":18},"ori":{"Shift":51},"sub":{"Shift":31}}},{"actions":{"addi":{"Shift":14},"sub":{"Shift":31},"or":{"Shift":36},"xor":{"Shift":18},"mv":{"Shift":6},"instructions":{"Shift":35},"nop":{"Shift":40},"and":{"Shift":41},"__$__":{"Reduce":{"left":"instructions","right":[]}},"cmp":{"Shift":47},"add":{"Shift":2},"lb":{"Shift":10},"sb":{"Shift":22},"andi":{"Shift":26},"hlt":{"Shift":30},"xori":{"Shift":55},"ori":{"Shift":51},"not":{"Shift":45},"li":{"Shift":59},"instruction":{"Shift":1}}},{"actions":{"register":{"Shift":3}}},{"actions":{"comma":{"Shift":4}}},{"actions":{"register":{"Shift":5}}},{"actions":{"sub":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["add","register","comma","register"]}}}},{"actions":{"register":{"Shift":7}}},{"actions":{"comma":{"Shift":8}}},{"actions":{"register":{"Shift":9}}},{"actions":{"sub":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["mv","register","comma","register"]}}}},{"actions":{"register":{"Shift":11}}},{"actions":{"comma":{"Shift":12}}},{"actions":{"number":{"Shift":13}}},{"actions":{"ori":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"not":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["lb","register","comma","number"]}}}},{"actions":{"register":{"Shift":15}}},{"actions":{"comma":{"Shift":16}}},{"actions":{"number":{"Shift":17}}},{"actions":{"not":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"ori":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["addi","register","comma","number"]}}}},{"actions":{"register":{"Shift":19}}},{"actions":{"comma":{"Shift":20}}},{"actions":{"register":{"Shift":21}}},{"actions":{"or":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"sub":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["xor","register","comma","register"]}}}},{"actions":{"register":{"Shift":23}}},{"actions":{"comma":{"Shift":24}}},{"actions":{"number":{"Shift":25}}},{"actions":{"not":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"ori":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["sb","register","comma","number"]}}}},{"actions":{"register":{"Shift":27}}},{"actions":{"comma":{"Shift":28}}},{"actions":{"number":{"Shift":29}}},{"actions":{"sub":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"ori":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"not":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["andi","register","comma","number"]}}}},{"actions":{"add":{"Reduce":{"left":"instruction","right":["hlt"]}},"__$__":{"Reduce":{"left":"instruction","right":["hlt"]}},"hlt":{"Reduce":{"left":"instruction","right":["hlt"]}},"sub":{"Reduce":{"left":"instruction","right":["hlt"]}},"and":{"Reduce":{"left":"instruction","right":["hlt"]}},"xor":{"Reduce":{"left":"instruction","right":["hlt"]}},"li":{"Reduce":{"left":"instruction","right":["hlt"]}},"not":{"Reduce":{"left":"instruction","right":["hlt"]}},"sb":{"Reduce":{"left":"instruction","right":["hlt"]}},"mv":{"Reduce":{"left":"instruction","right":["hlt"]}},"andi":{"Reduce":{"left":"instruction","right":["hlt"]}},"xori":{"Reduce":{"left":"instruction","right":["hlt"]}},"nop":{"Reduce":{"left":"instruction","right":["hlt"]}},"or":{"Reduce":{"left":"instruction","right":["hlt"]}},"ori":{"Reduce":{"left":"instruction","right":["hlt"]}},"addi":{"Reduce":{"left":"instruction","right":["hlt"]}},"cmp":{"Reduce":{"left":"instruction","right":["hlt"]}},"lb":{"Reduce":{"left":"instruction","right":["hlt"]}}}},{"actions":{"register":{"Shift":32}}},{"actions":{"comma":{"Shift":33}}},{"actions":{"register":{"Shift":34}}},{"actions":{"add":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"sub":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["sub","register","comma","register"]}}}},{"actions":{"__$__":{"Reduce":{"left":"instructions","right":["instruction","instructions"]}}}},{"actions":{"register":{"Shift":37}}},{"actions":{"comma":{"Shift":38}}},{"actions":{"register":{"Shift":39}}},{"actions":{"ori":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"sub":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["or","register","comma","register"]}}}},{"actions":{"addi":{"Reduce":{"left":"instruction","right":["nop"]}},"cmp":{"Reduce":{"left":"instruction","right":["nop"]}},"hlt":{"Reduce":{"left":"instruction","right":["nop"]}},"not":{"Reduce":{"left":"instruction","right":["nop"]}},"and":{"Reduce":{"left":"instruction","right":["nop"]}},"andi":{"Reduce":{"left":"instruction","right":["nop"]}},"xori":{"Reduce":{"left":"instruction","right":["nop"]}},"mv":{"Reduce":{"left":"instruction","right":["nop"]}},"nop":{"Reduce":{"left":"instruction","right":["nop"]}},"__$__":{"Reduce":{"left":"instruction","right":["nop"]}},"xor":{"Reduce":{"left":"instruction","right":["nop"]}},"sb":{"Reduce":{"left":"instruction","right":["nop"]}},"li":{"Reduce":{"left":"instruction","right":["nop"]}},"or":{"Reduce":{"left":"instruction","right":["nop"]}},"add":{"Reduce":{"left":"instruction","right":["nop"]}},"lb":{"Reduce":{"left":"instruction","right":["nop"]}},"sub":{"Reduce":{"left":"instruction","right":["nop"]}},"ori":{"Reduce":{"left":"instruction","right":["nop"]}}}},{"actions":{"register":{"Shift":42}}},{"actions":{"comma":{"Shift":43}}},{"actions":{"register":{"Shift":44}}},{"actions":{"xori":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"sub":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"not":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["and","register","comma","register"]}}}},{"actions":{"register":{"Shift":46}}},{"actions":{"mv":{"Reduce":{"left":"instruction","right":["not","register"]}},"not":{"Reduce":{"left":"instruction","right":["not","register"]}},"and":{"Reduce":{"left":"instruction","right":["not","register"]}},"or":{"Reduce":{"left":"instruction","right":["not","register"]}},"sb":{"Reduce":{"left":"instruction","right":["not","register"]}},"xor":{"Reduce":{"left":"instruction","right":["not","register"]}},"andi":{"Reduce":{"left":"instruction","right":["not","register"]}},"ori":{"Reduce":{"left":"instruction","right":["not","register"]}},"xori":{"Reduce":{"left":"instruction","right":["not","register"]}},"li":{"Reduce":{"left":"instruction","right":["not","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["not","register"]}},"lb":{"Reduce":{"left":"instruction","right":["not","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["not","register"]}},"sub":{"Reduce":{"left":"instruction","right":["not","register"]}},"add":{"Reduce":{"left":"instruction","right":["not","register"]}},"nop":{"Reduce":{"left":"instruction","right":["not","register"]}},"addi":{"Reduce":{"left":"instruction","right":["not","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["not","register"]}}}},{"actions":{"register":{"Shift":48}}},{"actions":{"comma":{"Shift":49}}},{"actions":{"register":{"Shift":50}}},{"actions":{"not":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"cmp":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"nop":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"lb":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"andi":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"xori":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"__$__":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"hlt":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"and":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"ori":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"sub":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"addi":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"xor":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"sb":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"mv":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"or":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"li":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}},"add":{"Reduce":{"left":"instruction","right":["cmp","register","comma","register"]}}}},{"actions":{"register":{"Shift":52}}},{"actions":{"comma":{"Shift":53}}},{"actions":{"number":{"Shift":54}}},{"actions":{"xori":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"ori":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"not":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["ori","register","comma","number"]}}}},{"actions":{"register":{"Shift":56}}},{"actions":{"comma":{"Shift":57}}},{"actions":{"number":{"Shift":58}}},{"actions":{"ori":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"mv":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"not":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["xori","register","comma","number"]}}}},{"actions":{"register":{"Shift":60}}},{"actions":{"comma":{"Shift":61}}},{"actions":{"number":{"Shift":62}}},{"actions":{"mv":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"nop":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"xori":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"add":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"or":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"sub":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"li":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"__$__":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"hlt":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"andi":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"not":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"cmp":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"xor":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"lb":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"sb":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"and":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"ori":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}},"addi":{"Reduce":{"left":"instruction","right":["li","register","comma","number"]}}}},{"actions":{"__$__":{"Reduce":{"left":"program","right":["instructions"]}}}},{"actions":{"__$__":{"Reduce":{"left":"S","right":["program"]}}}},{"actions":{"__$__":{"Reduce":{"left":"__DUMMY_START__","right":["S"]}}}}]}"#).unwrap();
        // ======================

        let mut handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>> =
            HashMap::new();

        // handlers generated by rparser
        // ======================
        handlers.insert(
            ReduceDerivation::build("S".into(), vec!["program".into()]),
            Box::new(|datas| {
                println!("S -> program");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("program".into(), vec!["instructions".into()]),
            Box::new(|datas| {
                println!("program -> instructions");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instructions".into(),
                vec!["instruction".into(), "instructions".into()],
            ),
            Box::new(|datas| {
                println!("instructions -> instruction instructions");
                format!("{} {}", datas[0], datas[1])
            }),
        );
        handlers.insert(
            ReduceDerivation::build("instructions".into(), vec![]),
            Box::new(|datas| {
                println!("instructions -> ε");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "li".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> li register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::LI as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "mv".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> li register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::MV as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "lb".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> lb register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::LB as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "sb".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> sb register comma number");

                let src = Register::from_str(&datas[1]).unwrap() as u8;
                let dst = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::SB as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "add".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> add register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::ADD as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "addi".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> addi register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::ADDI as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "sub".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> sub register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::SUB as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "and".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> and register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::AND as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "andi".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> andi register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::ANDI as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "or".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> or register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::OR as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "ori".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> ori register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::ORI as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "xor".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> xor register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::XOR as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "xori".into(),
                    "register".into(),
                    "comma".into(),
                    "number".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> xori register comma number");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = u8::from_str_radix(&datas[3], 10).unwrap();
                format!("{:02X} {:02X} {:02X}", Instruction::XORI as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build("instruction".into(), vec!["not".into(), "register".into()]),
            Box::new(|datas| {
                println!("instruction -> not register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::XOR as u8, dst, 0)
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "instruction".into(),
                vec![
                    "cmp".into(),
                    "register".into(),
                    "comma".into(),
                    "register".into(),
                ],
            ),
            Box::new(|datas| {
                println!("instruction -> cmp register comma register");

                let dst = Register::from_str(&datas[1]).unwrap() as u8;
                let src = Register::from_str(&datas[3]).unwrap() as u8;
                format!("{:02X} {:02X} {:02X}", Instruction::CMP as u8, dst, src)
            }),
        );
        handlers.insert(
            ReduceDerivation::build("instruction".into(), vec!["nop".into()]),
            Box::new(|datas| {
                println!("instruction -> nop");
                format!("{:02X} 00 00", Instruction::NOP as u8)
            }),
        );
        handlers.insert(
            ReduceDerivation::build("instruction".into(), vec!["hlt".into()]),
            Box::new(|datas| {
                println!("instruction -> hlt");
                format!("{:02X} 00 00", Instruction::HLT as u8)
            }),
        );
        // ======================

        handlers.insert(
            ReduceDerivation::build(Self::DUMMY_START_SYMBOL.into(), vec!["S".into()]),
            Box::new(|vals| vals[0].clone()),
        );

        let mut res: RParser = RParser::default();
        res.action_table = action_table;
        res.handlers = handlers;
        res
    }

    // do shift-reduce parsing
    pub fn parse<T>(&self, tokens: Vec<T>) -> Result<ParsingTreeNode, Box<dyn Error>>
    where
        T: Token,
    {
        let mut shift_index = 0;
        let mut stack: Vec<NodePair> = Vec::new();

        stack.push(NodePair::new(
            ParsingTreeNode::build(Self::DUMMY_START_SYMBOL.into(), String::new(), Vec::new()),
            0,
        ));

        loop {
            let token_node = &tokens[shift_index].to_tree_node();

            let action = self
                .action_table
                .get_action(stack.last().unwrap().1, &token_node.symbol_type);

            match action {
                Some(Action::Shift(next_state)) => {
                    // shift
                    stack.push(NodePair::new(
                        tokens[shift_index].to_tree_node(),
                        *next_state,
                    ));
                    shift_index += 1;
                }
                Some(Action::Reduce(derivation)) => {
                    // pop right hand
                    let mut children: Vec<ParsingTreeNode> = Vec::new();
                    let mut datas = Vec::new();
                    for _ in 0..derivation.right.len() {
                        if let Some(top) = stack.pop() {
                            datas.push(top.0.data.clone());
                            children.push(top.0);
                        } else {
                            Err("parsing error: stack is empty.")?;
                        }
                    }

                    let children: Vec<_> = children.into_iter().rev().collect();
                    let datas: Vec<_> = datas.into_iter().rev().collect();
                    let handler = self.handlers.get(&derivation).unwrap();

                    // if the left hand side is dummy start symbol
                    // do nothing
                    if derivation.left == Self::DUMMY_START_SYMBOL {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            0,
                        ));
                        continue;
                    }

                    // goto[top_state(stack), X]
                    if let Action::Shift(next_state) = self
                        .action_table
                        .get_action(stack.last().unwrap().1, &derivation.left)
                        .unwrap()
                    {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            *next_state,
                        ));
                    } else {
                        Err("parsing error: invalid Shift action.")?;
                    }
                }
                Some(Action::Accept) => {
                    let res = stack.pop().unwrap().0;
                    return Ok(res);
                }
                _ => {
                    Err("parsing error: unknown.")?;
                }
            }
        }
    }
}
